### ISSUE TITLE
multiple domain with single public ip use case

### ISSUE THREAD

**Issue by sicenul** [staticfloat/docker-nginx-certbot#25]
Can I use your docker certbot for my case? if possible this is the case:

* I have one public IP and want to serve using your docker-compose.
* I have two container, each located on difference server, serving example.com website and example.org website
* example.com DNS A Record will be pointed to that public IP.
* example.org DNS A Record also will be pointed to that same public IP.

Is it possible? By using something like this config, and put it inside `conf.d`?:
```
# In conf.d/examplecom.conf
server {
    listen              443 ssl;
    server_name         example.com;
    ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    location / {
        proxy_pass http://192.168.11.2:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
```
# In conf.d/exampleorg.conf
server {
    listen              443 ssl;
    server_name         example.org;
    ssl_certificate     /etc/letsencrypt/live/example.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem;

    location / {
        proxy_pass http://192.168.12.2:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
![image](https://user-images.githubusercontent.com/64000634/87654036-95220f00-c780-11ea-9d90-828adace727f.png)

**Comment by exesse** [comment]
@sicenul Hi, absolutely possible! 

````
server {
  listen 443 ssl;
  server_name example.org;
  server_tokens off;
  ssl_certificate     /etc/letsencrypt/live/example.org/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  location / {
          proxy_pass http://YOUR_TARGET_IP/;
          proxy_set_header Host $host;
                }
}

server {
  listen 443 ssl;
  server_name example.com;
  server_tokens off;
  ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
  location / {
          proxy_pass http://YOUR_TARGET_IP:port;
          proxy_set_header Host $host;
                }
}
````

And even more if the load is not huge you may want to combine everything as one docker-compose file.

**Comment by sicenul** [comment]
Thanks, will try it.
Another question:
1. Since this is a test, How to use staging server for lets encrypt?
1. Is it possible if I don't want to use https on the second config? how? Maybe just listen to port 80 like this:
```
server {
  listen 80;
  server_name example.com;
  server_tokens off;

  location / {
          proxy_pass http://YOUR_TARGET_IP:port;
          proxy_set_header Host $host;
                }
}
```

**Comment by exesse** [comment]
@sicenul just use official nginx docker image for that. On the other hand you may create couple subdomains for your testing environment and simply change `server_name` entries for production config.

**Comment by exesse** [comment]
@staticfloat please close the issue.

**Comment by sicenul** [comment]
@exesse , I mean the first question is lets encrypt staging server. And the second question is still using this docker but we can decide which container using http only, and which container using https.

Thank you for your valuable time in responding my question. I'm closing this question.
